JUMPKEY = "up"
SLIDEKEY = "down"
SWORDKEY = "right"
FORESTDATA = " --- ooo 888 rrr "
GODMODE = false

STATEMENU = 0
STATEGAME = 1
STATEWIN = 2
STATEFAIL = 3
MAXHEALTH = 3
SPACEBETWEENHEARTS = 18
HEARTX = 5
HEARTY = 5

INFOX = 300
INFOY = 300