JUMPKEY = "up"
SLIDEKEY = "down"
SWORDKEY = "right"
FORESTDATA = " ---ooo888rrr"
CAVEDATA = " -o8-o8-o8rrr"
HAUNTEDDATA = " -o88o--o8rrr"
MAXHEALTH = 9
SPACEBETWEENHEARTS = 18
HEARTX = 5
HEARTY = 5
XPLEVEL = 4

STATX = 100
STATY = 150
STATDIFF = 40

-- possible change this depending on world
REACTIONTIME = 0.2

INFOX = 300
INFOY = 300