JUMPKEY = "up"
SLIDEKEY = "down"
SWORDKEY = "right"
FORESTDATA = " ---ooo888"
CAVEDATA = " -o8-o8-o8"
HAUNTEDDATA = " -o88o--o8"
GODMODE = true
MAXHEALTH = 3
SPACEBETWEENHEARTS = 18
HEARTX = 5
HEARTY = 5

INFOX = 300
INFOY = 300